# Generated by Django 4.2.6 on 2023-10-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='blank-profile-picture.jpeg', upload_to='profile_images'),
        ),
    ]
